export default {
    REGISTRATION: 'REGISTRATION_USER',
    GET_USERS: 'GET_USERS',
    LOGIN: 'LOGIN_USER',
    LOGOUT: 'LOGOUT_USER',
    GET_CURRENT_USER: 'GET_CURRENT_USER',
    GET_USER: 'GET_USER',
    CHANGE_CURRENT_USER: 'CHANGE_CURRENT_USER',
    CREATE_POST: 'CREATE_POST',
    GET_POST_BY_ID: 'GET_POST_BY_ID',
    GET_USER_BY_ID: 'GET_USER_BY_ID',
    GET_USERS_BY_LOGIN: 'GET_USERS_BY_LOGIN',
    GET_FEED: 'GET_FEED'
}